/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pnote

import com.googlecode.lanterna.TextColor
import kotlinx.coroutines.runBlocking
import pnote.projections.projectBrowseNotes
import pnote.projections.sandbox.BoxContext
import pnote.projections.sandbox.BoxScreen
import pnote.projections.sandbox.ColorSwatch
import pnote.projections.sandbox.lanternaBoxScreen
import pnote.scopes.AppScope
import pnote.stories.browseNotesStory
import pnote.tools.*
import java.io.File

fun userDir(commandName: String, userName: String): File {
    val homeDir = System.getProperty("user.home")!!.also { check(it.isNotBlank()) }
    val appDir = homeDir.let { home -> File(home, ".$commandName").apply { mkdirs() } }
    return appDir.let { app -> File(app, userName).apply { mkdirs() } }
}

class App(commandName: String, userName: String) : AppScope {
    private val userDir = userDir(commandName, userName)
    override val cryptor: Cryptor = memCryptor()
    override val noteBag: NoteBag = FileNoteBag(userDir, cryptor)
    override val logTag: String = commandName
}

fun main(args: Array<String>) {
    val commandSuffix = args.getOrNull(0)?.let { "-debug" } ?: ""
    val commandName = "pnote$commandSuffix"
    val app = App(commandName, "main")
    val story = app.browseNotesStory()
    runBlocking {
        val boxContext = mainBoxContext()
        boxContext.projectBrowseNotes(story).join()
        boxContext.boxScreen.close()
    }
}

fun mainBoxContext(block: (BoxContext.() -> Unit)? = null): BoxContext {
    val context = object : BoxContext {
        override val boxScreen: BoxScreen = lanternaBoxScreen()
        override val surfaceSwatch: ColorSwatch =
            ColorSwatch(TextColor.ANSI.WHITE, TextColor.Indexed.fromRGB(0x36, 0x36, 0x40))
        override val backgroundSwatch: ColorSwatch =
            ColorSwatch(TextColor.ANSI.WHITE, TextColor.Indexed.fromRGB(0x12, 0x12, 0x12))
        override val primarySwatch: ColorSwatch =
            ColorSwatch(TextColor.ANSI.WHITE, TextColor.Indexed.fromRGB(0x5c, 0x6b, 0xc0))
        override val primaryDarkSwatch: ColorSwatch =
            ColorSwatch(TextColor.ANSI.WHITE, TextColor.Indexed.fromRGB(0x26, 0x41, 0x8f))
        override val primaryLightSwatch: ColorSwatch =
            ColorSwatch(TextColor.ANSI.BLACK, TextColor.Indexed.fromRGB(0x8e, 0x99, 0xf3))
        override val secondarySwatch: ColorSwatch =
            ColorSwatch(TextColor.ANSI.BLACK, TextColor.Indexed.fromRGB(0xc5, 0xe1, 0xa5))
        override val errorSwatch: ColorSwatch =
            ColorSwatch(TextColor.ANSI.BLACK, TextColor.ANSI.RED)
    }
    return context.also { block?.invoke(it) }
}
